### ISSUE TITLE
[color-chart] Add support for `ymin` and `ymax` props

### ISSUE THREAD

**Issue by DmitrySharabin** [color-js/elements#120]
As @LeaVerou mentioned in our conversation, we need a way to control whether the bounds the chart is built within are “tight” (the current behavior), i.e., determined by the data, encompassing the whole range of the coordinate or a custom min and max.

It can be accomplished by supporting two new props: `ymin` and `ymax` (these names seem more readable than possible `miny` and `maxy`).

They should (?) support two keywords: `auto` and `coord` (`range`?)—and numbers as values.

### Usage examples

`<color-chart y="oklch.h">...</color-chart>` — `ymin="auto"`, `ymax="auto"` _(default)_

`<color-chart y="oklch.h" ymin="20">...</color-chart>`

`<color-chart y="oklch.h" ymax="135">...</color-chart>`

`<color-chart y="oklch.h" ymin="20" ymax="135">...</color-chart>`

`<color-chart y="oklch.h" ymin="coord">...</color-chart>` — the minimum value of the Y-axis should be taken from the coord’s (in this case, `oklch.h`) range. `ymin` might be less than the minimum value for all color points in the chart.

**Q:** What type should these props have?

I wonder if there is a way to extend the built-in `Number` class to support two new props (`auto` and `coord`) similarly to `NaN`. Or we can probably declare our own class that works with numbers like the built-in one `Number` class but has two extra properties?

**Comment by DmitrySharabin** [comment]
I'm leaning towards defining these props something like this:

```js
ymin: {
	convert (value) {
		// Is a supported keyword?
		if (["auto", "coord"].includes(value)) {
			if (value === "coord") {
				let range = this.yResolved.range ?? this.yResolved.refRange;
				return range?.[0];
			}

			return value;
		}

		return Number(value);
	},
},
```

Is it illegal?

**Comment by DmitrySharabin** [comment]
I have a prototype to discuss (ready to submit a draft PR so we can iterate). Here is it in action:


https://github.com/user-attachments/assets/4ca060f7-a041-4611-a22f-71843a4dde9e

And another one question:

![image](https://github.com/user-attachments/assets/ab79e2e1-2c0a-4103-a7c5-587af4705d38)

**Comment by LeaVerou** [comment]
Awesome, thanks!

I wouldn't expect them to be _disconnected_. I'd expect them to have lines that go out of range, in the direction of the data points. Essentially drawing the whole thing, but applying `overflow: hidden` to the chart.

**Comment by DmitrySharabin** [comment]
> I wouldn't expect them to be _disconnected_. I'd expect them to have lines that go out of range, in the direction of the data points. Essentially drawing the whole thing, but applying `overflow: hidden` to the chart.

OK, that makes sense. One thing that bothers me with `overflow: hidden` is that every chart-related element that happens to be partially outside the chart container will be clipped—for example, tooltips.

<img width="224" alt="image" src="https://github.com/user-attachments/assets/e433b901-cb30-49f0-a458-3fb5fed1b08c">

Other than that, `overflow: hidden` works nice.

**Comment by DmitrySharabin** [comment]
> OK, that makes sense. One thing that bothers me with `overflow: hidden` is that every chart-related element that happens to be partially outside the chart container will be clipped—for example, tooltips.

One option would be here to change the tooltip position to leave it inside the chart container all the time. I wonder if the [CSS anchor positioning API](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_anchor_positioning) will help here. 🤔

**Comment by LeaVerou** [comment]
We should add the `popover` attribute to these, then they won't be affected.

**Comment by LeaVerou** [comment]
Should we close this, since these are implemented?

**Comment by DmitrySharabin** [comment]
> Should we close this, since these are implemented?

We definitely should. 🙂

Implemented in https://github.com/color-js/elements/commit/0813ef7c1952caba743275c867dadc48efca2d4d
