### ISSUE TITLE
`<color-gamut>` (and other elements which use it) is broken in Safari

### ISSUE THREAD

**Issue by DmitrySharabin** [color-js/elements#13]
The `Color` object imported from a (dynamically downloaded) module (`https://colorjs.io/dist/color.js`) 

https://github.com/color-js/elements/blob/31a14ba86cb155c2e92fa78ca832b743937529d8/src/common/color.js#L12

is treated by Safari as an uninitialized variable.

As a result, this line throws `ReferenceError: Cannot access uninitialized variable`.

https://github.com/color-js/elements/blob/31a14ba86cb155c2e92fa78ca832b743937529d8/src/color-gamut/color-gamut.js#L154

**Comment by DmitrySharabin** [comment]
If it's in the browser cache, it might begin working on user interaction. See [the demo](https://arc.net/l/quote/rcepqqyf) on the `<color-gamut>` page.

**Comment by DmitrySharabin** [comment]
If we don't fix issues with other components by fixing this issue, I'll file separate issues for them. For now, it's unclear whether they don't work because of `<color-gamut>` or have some other issues.

**Comment by DmitrySharabin** [comment]
My investigation showed that this issue might be related to top-level `await` ([a known issue in Safari](https://bugs.webkit.org/show_bug.cgi?id=242740)) in `common/color.js`:

https://github.com/color-js/elements/blob/8b96596315a434491187ac4f2755dfb574b02a46/src/common/color.js#L12

**Comment by LeaVerou** [comment]
It's this WebKit bug: https://bugs.webkit.org/show_bug.cgi?id=242740

**Comment by LeaVerou** [comment]
Now that this is fixed, we need to document what other bugs the components have in Safari. From a quick look, I did spot a few…
