### ISSUE TITLE
Feature Request: <color-swatch> remove formatting from shadowStyle

### ISSUE THREAD

**Issue by sidewayss** [color-js/elements#159]
I am working with `<color-swatch>` and it's a pain to work around `color-swatch.css`.  It even seems to style my slotted `<input>` element! No offense, but I want my styles, not yours.  I like having yours as an example, a reference. Maybe for a different web page I'd even want to import them.  I am now starting to wrap `<color-picker>` in a `<dialog>` and I will certainly want the default swatch formatting there.

I realize that there are variables defined in these CSS files and that you are using them internally. But properties like padding, margin, and border-radius should not be in there.  It forces the user to override all those for their own purposes. My original element, the one that this swatch is replacing, is also a `<div>`, and it inherits styles from other places.  I am even having difficulty overriding the `flex` settings here in order to lay this out the same way as before.

The more I look at it, the more I see being styled by this CSS file.  I want a `#swatch` that is just a `<div>`, without what looks like a somewhat complex web of styles you have going.  It looks like you slot or otherwise insert elements inside `#swatch`, so that might make this more difficult.  But you even set minimum sizes for `#swatch`, which is extremely restrictive IMO.  In my case I bump up against `min-inline-size` here because my swatch is a 1.5625rem (25px) square, and this restricts the width:
```css
slot[name="swatch"]::slotted(*), #swatch {
    &:not(:host([size="large"]) *) {
        display: flex;
        min-inline-size: 2em;
        min-block-size: 1em;
        font-size: 65%;
        flex: 1;
    }
}}
```

One solution would be to separate out these properties into a new CSS file that the user can import into their HTML file if they want the default formats.  I assume this is the same for other elements, but I haven't gotten around to using any of them yet.

Here's it is in color-swatch.js:
https://github.com/color-js/elements/blob/a7e97578bbe20d671e67263361f6a8f8c4093ba3/src/color-swatch/color-swatch.js#L10

And here in common/color-element.js:
https://github.com/color-js/elements/blob/a7e97578bbe20d671e67263361f6a8f8c4093ba3/src/common/color-element.js#L31

**Comment by LeaVerou** [comment]
Sounds like we may be using overly high specificity. @DmitrySharabin could you check?
@sidewayss it would be useful for us to see what you're trying to do with `<color-swatch>` and where the styles conflict.

**Comment by sidewayss** [comment]
See my `<color-button>` prototype here: https://sidewayss.github.io/rAF/apps/color/

In the 2nd and 3rd row of the form, labeled `Start:` and `End:`, at the far right are two `<button>`s with colored `<div>`s inside them: `#startSwatch` and `#endSwatch`.  I would prefer those to be swatches, but it's a pain to style them to have no padding, margin, or border-radius, among other properties.  Source code is here: https://github.com/sidewayss/rAF/tree/main/apps/color

Also see the slotted `<input>` inside the `<color-picker>` that pops up in a `<dialog>` when you click on those buttons.  I had trouble styling that too, though that's inside `<color-picker>` not a swatch.  The picker has a similar CSS file.  (at least that's my memory of why I mentioned the `<input>` styling in the original issue post).

**Comment by DmitrySharabin** [comment]
Honestly, I don't see any issues in this case. @sidewayss, please take a look at this pen — I recreated your color swatch button there. I don't think there are more CSS rules than you already use: https://codepen.io/dmitrysharabin/pen/EaYVzZP.

If you can point me to the exact issues with the color picker, I might help with it, too.

**Comment by sidewayss** [comment]
So the keys here are a combination of  `all:unset` and `&` as a selector, two things with which I am previously unfamiliar and will have to search for and read about now.  Thanks for the CSS lesson!  And thanks for the offer on the color picker input, but I am not using it at this time, so it's moot.
