### ISSUE TITLE
Accessibility and <label for="color-element-id">: formAssociated and attachInternals()

### ISSUE THREAD

**Issue by sidewayss** [color-js/elements#175]
I just now discovered these while working through the tangle that is focus for an autonomous custom element.  There are no docs beyond the spec that I could find for `formAssociated`.  Docs for `attachInternals()` are [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals).  I got them working for my elements easily enough.  They allows you to attach a `<label>` to a custom element, for example.  All I had to do was put these lines inside my base class:
```js
class Base {
    #internals;
    static formAssociated = true;
    constructor() {
        this.#internals = attachInternals();
}
```
`#internals` is probably not necessary.  I haven't found a reason a reference it, but I only just added it, so it might come up.

If you're interested in accessibility or simply attaching a label to one of your elements, this is it.  In CSS it also allows you to use `:disabled` and  `:checked` instead of `[disabled]` and `[checked]`. It would certainly seem to do no harm, but I've never dabbled in accessibility or ARIA before.  Here's a more complete example in the spec, if that helps: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-face-example

A couple of caveats regarding `<label for="custom-elm-id">`: 
- When the `htmlFor` element is disabled, the label still reacts and styles the disabled element using `:hover` and `:active`.
- Custom elements don't get a [`labels`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/labels) property like `HTMLInputElement`.  Acquiring the list is as simple as **querySelectorAll(\`[for="${this.id}"]\`)**. You need it to set `label.pointerEvents = "none"` to work around the first caveat.

As for the larger focus issue, that's a separate topic and I haven't tested it on your elements.  I don't see you managing `disabled` or `tabindex` attributes.  That, along with `pointer-events`, is part of the puzzle because `HTMLElement` has `tabindex` but not `disabled`. So you have to create `disabled` and manage it. Mixing focusable and unfocusable elements inside your template can complicate focus too.  This is all assuming that the custom element is autonomous, inheriting from `HTMLElement`.

**Comment by LeaVerou** [comment]
@sidewayss I think there is a lot of context missing here. Could you please elaborate on what issue this is solving, how it is solving it, and what you are proposing? I cannot connect it to anything besides adding support for `disabled` (which we should probably do in [Nude Element](https://github.com/nudeui/element), either as a separate mixin, or possibly also as a part of the [formAssociated mixin](https://github.com/nudeui/element/tree/main/src/formAssociated.js))

**Comment by sidewayss** [comment]
Well, I was unaware of your formAsssociated mixin, so that could be a big part of it.  If you are already setting `Class.formAssociated = true` and `attachInternals()`, then nevermind that.

As for the focus bit, yet there's `disabled` and `tabindex`. I don't know how you intend to manage focus for these elements, so I'm missing context too. I just went through dealing with it for a numeric input, which has keyboard access too.  There's a whole lot of funk there, and some browser-specificness.

And the bit about labels is worth handling, if you expect to attach them to any of your elements with the `for` attribute.  If you'd prefer to close this and deal with any of these other two issues separately, please go ahead.

**Comment by LeaVerou** [comment]
@sidewayss I’m still missing a lot of context. What problem are you seeing? Are there labels that are not hooked up properly? Is focus not managed properly? What happens? What should happen? Step back for a second and explain the problems **before** diving into how to solve them. 

> If you are already setting `Class.formAssociated = true` and `attachInternals()`, then nevermind that.

It is. So I would have expected that just using labels as normal should work?

**Comment by sidewayss** [comment]
Sorry for the misunderstanding.  The labels issue I mention as "caveats" in the opening comment only happens when the associated form element is disabled.  So it should be part of any disabled implementation.

I you like I can open an issue in NudeElements about `disabled` and mention the label side-issue.  Otherwise I'll leave that up to you.  I'll close this issue with this comment.

I see that `<color-picker>` and `<color-scale>` are not form-associated.  Is `<color-scale>` ever intended to be used as a picker? That was my first thought for using it, was to pick a shade of a color.
