### ISSUE TITLE
[color-slider][channel-slider][space-picker]: Feature request =  .labels property

### ISSUE THREAD

**Issue by sidewayss** [color-js/elements#178]
https://codepen.io/sidewayss/pen/Wbevapq

Open the console in CodePen and compare to JavaScript pane:
- for both these elements `.labels` is undefined

IMO:
- This must be a "live" property, fetching the labels on-demand.  Users might add labels dynamically, as unlikely as that is.
- It should return an array, not a `NodeList`.  That's just a convenience.
- It might look like this:
```js
get labels() { 
    return [...document.querySelectorAll(`[for="${this.id}"]`)];
}
```

**Comment by LeaVerou** [comment]
@DmitrySharabin (or @sidewayss) could you open a Nude Element issue? I think the formAssociated plugin should do this by default.

**Comment by DmitrySharabin** [comment]
> I think the formAssociated plugin should do this by default.

Actually, it does. We just need to wait for the custom elements to be defined.

@sidewayss, this code snippet should help:

```js
Promise.all([
  customElements.whenDefined("color-slider"),
  customElements.whenDefined("space-picker")
]).then(() => {
  console.log("slider.labels:", slider.labels);
  console.log("picker.labels:", picker.labels);
});
```

<img width="321" alt="image" src="https://github.com/user-attachments/assets/d02a724c-e0bb-43dc-a0ea-d8372361aa7d">

**Comment by sidewayss** [comment]
Ah yes, `customElements.whenDefined()`.  I have used that.  It didn't occur to me here, but it should have.  Maybe then this merits a mention in the documentation?  Certainly easy to forget or simply not know about it.
