### ISSUE TITLE
Should the `PropChangeEvent` subclasses exist?

### ISSUE THREAD

**Issue by LeaVerou** [color-js/elements#27]
I was just looking at https://w3ctag.github.io/design-principles/#state-and-subclassing and wondered if we should not have these. It would make the code simpler, and we can just use e.g. `this.color` instead of `event.color`.

**Comment by DmitrySharabin** [comment]
If we can achieve everything we need with the `Event` object and simplify our code, I'm all for it.

I also see another very personal benefit—I can be more productive in helping you maintain the codebase. 🙃

**Comment by DmitrySharabin** [comment]
> No, we’d still have `PropChangeEvent`, just not its subclasses. E.g. `valuechange` would be an instance of `PropChangeEvent`.

Oh, I see. 🤦‍♂️

But you have the motivation to go this route in the first place. Are those motives still relevant?

**Comment by LeaVerou** [comment]
I think I thought it would be convenient to have the property directly on the event object, but I think it was misguided.

**Comment by DmitrySharabin** [comment]
Well, probably it's high time for another iteration then. 👀

**Comment by LeaVerou** [comment]
Removed these in the new [Element](https://github.com/nudeui/element) helper, so closing.
