### ISSUE TITLE
[color-picker] No sliders if no `space` is provided

### ISSUE THREAD

**Issue by LeaVerou** [color-js/elements#39]
It would be nice to just default to the color space of the color provided. Or even a predefined one, like oklch.

Testcase: https://codepen.io/leaverou/pen/ExzVaPO

Edit: there is actually a static default one, `oklch`. Need to debug why it's not working!

**Comment by DmitrySharabin** [comment]
The default space is a string, but we need this to be an instance of the corresponding color space (we generate the sliders based on `this.space.cords`):

https://github.com/color-js/elements/blob/2135f503352281d6fbedfb151b65fb619618b27b/src/color-picker/color-picker.js#L72

So, the default value is not parsed but should (already filed [the related issue on Nude Element](https://github.com/nudeui/element/issues/7)).

**Comment by DmitrySharabin** [comment]
I have a fix (I wouldn't say I like it much, though) in case we need something quick (and dirty 😅)

```js
propChangedCallback ({name, prop, detail: change}) {
	if (name === "space") {
		if (typeof this.space === "string") {
			this.space = prop.parse(this.space);
		}

		...
}
```

**Comment by DmitrySharabin** [comment]
It seems to me I could find (or become a bit closer to) a better (more general) solution: https://github.com/nudeui/element/pull/9.

**Comment by DmitrySharabin** [comment]
This will be fixed automatically as soon as we have a new release of NudeUI Element, so I'm going to close it.
