### ISSUE TITLE
Harmonize CSS custom properties concerning transparency across all components that have a transparency grid

### ISSUE THREAD

**Issue by DmitrySharabin** [color-js/elements#62]
### Components
- [x] `<color-inline>`
- [x] `<color-slider>`
- [x] `<color-swatch>`

**Comment by DmitrySharabin** [comment]
| `<color-inline>` | `<color-slider>` | `<color-swatch>` | Result |
|--------|--------|--------|--------|
| `--transparency-grid` | `--transparency` | `--transparency` | ? |
| `--transparency-tile-size` | - | `--transparency-cell-size` | ? |
| - | - | `--transparency-darkness` | `--transparency-darkness` |
| - | - | `--transparency-background` | `--transparency-background` |

**Comment by LeaVerou** [comment]
Thanks for doing that research! 

Yeah let's go for `--transparency-grid`, `--transparency-cell-size`, `--transparency-darkness`, `--transparency-background` for all of them.
