### ISSUE TITLE
[color-inline] Rewrite to inherit from NudeElement

### ISSUE THREAD

**Issue by LeaVerou** [color-js/elements#72]
`<color-inline>` is now our last component to not use Nude Element helpers.

Its API should be very similar to `<color-swatch>`, without the editing stuff.

@DmitrySharabin do you think you may be up to this?

**Comment by DmitrySharabin** [comment]
> @DmitrySharabin do you think you may be up to this?

With great pleasure! I need to try adopting the new API to solidify my knowledge.
