### ISSUE TITLE
[color-swatch] Regression: Gamut badge seems to be using its defaults, instead of the values passed by `<color-swatch>`

### ISSUE THREAD

**Issue by LeaVerou** [color-js/elements#79]

**Comment by DmitrySharabin** [comment]
Do you have an example of how this happens? I looked through the examples we have, and they seem fine. I can't see anything weird—I checked `gamuts` and `color`.

`<color-swatch>` has `gamuts` equal to `"srgb, p3, rec2020: P3+, prophoto: PP"`, `<gamut-badge>`—`srgb, p3, rec2020, prophoto`. They are the same, but some have labels.

What am I missing?

**Comment by LeaVerou** [comment]
Does this example look different on your end? 

<img width="1003" alt="image" src="https://github.com/color-js/elements/assets/175836/1f7f638b-ca3f-4b95-a6ad-f22bd78e51f2">

**Comment by DmitrySharabin** [comment]
> Does this example look different on your end?

Nope. It looks the same.

Now I see what you mean—its label should be `P3+`, right?

Investigating...

**Comment by LeaVerou** [comment]
Yup!
