### ISSUE TITLE
[color-swatch] Regression: If `color` is set programmatically, `value` doesn't update

### ISSUE THREAD

**Issue by DmitrySharabin** [color-js/elements#85]
[Testcase](https://codepen.io/dmitrysharabin/pen/WNBjLYy)

```html
<color-swatch id="dynamic_static">oklch(70% 0.25 138)</color-swatch>
<button onclick='dynamic_static.color = "oklch(60% 0.15 0)"'>Change color</button>
```

**Comment by DmitrySharabin** [comment]
One more thing to note. If `<color-swatch>` is editable after the color is set programmatically, changing the value in `<input>` no longer updates the color. The link between `value` and `color` is broken after the color change.

**Comment by DmitrySharabin** [comment]
> The link between `value` and `color` is broken after the color change.

OK, this is why it happens (at least, as far as I can see).

`value` is the default prop for `color`:  https://github.com/color-js/elements/blob/92cb2e0f8a7beb09eb4f23f807ff2f03b58e82c9/src/color-swatch/color-swatch.js#L134
Every time we update `value`, `color`, as a dependent of `value`, is also updated. This happens because [`dependsOn()`](https://github.com/nudeui/element/blob/924a27fb979f1b38e0b3e6b8897159759350ca5e/src/props/Prop.js#L290-L301)
returns `true`.

But why does it return `true` in our case? Because of [this line](https://github.com/nudeui/element/blob/924a27fb979f1b38e0b3e6b8897159759350ca5e/src/props/Prop.js#L300):
```js
this.defaultProp === prop && element.props[this.name] === undefined
```
`value` is the `color` default prop and `element.props["color"] === undefined` (since we haven't set it programmatically yet).

When we set `color` programmatically, we [set the corresponding prop on the element](https://github.com/nudeui/element/blob/924a27fb979f1b38e0b3e6b8897159759350ca5e/src/props/Prop.js#L196). This means `element.props["color"]` is not `undefined` anymore. In its turn, it means that `dependsOn()` will return `false` when the `value` prop updates, and the dependent (`color`) won't be updated—changes to `value` won't be propagated to `color`.

I wonder, what should be done in this situation?

- `value` should not be the default prop for `color` and `color`, in its turn, should get its default value the other way?
- When setting a value to a prop that has a default prop, should we update the default prop accordingly and not set `element.props[...]` for this prop to preserve the link between the prop and its default prop?
- We should update the logic of `dependsOn()` to cover such cases?

**Comment by DmitrySharabin** [comment]
> `value` should not be the default prop for `color` and `color`, in its turn, should get its default value the other way?

I tried this. If we replace `defaultProp` with a getter and a setter (and one tiny change in `propChangedCallback()`), the issue with editable swatches will be fixed. It also fixes [the issue with `<color-picker>`](https://github.com/color-js/elements/issues/84) in one shot.

**Comment by LeaVerou** [comment]
Another solution is to implement https://github.com/nudeui/element/issues/24 which would handle keeping them in sync automatically.

**Comment by DmitrySharabin** [comment]
For now, [we decided to go with a getter and setter](f61894335e6d4f64bc2fddd110292067069d6fa2) (as a workaround) to make the stuff work again.
