### ISSUE TITLE
[color-scale] Fails to parse functional colors with commas

### ISSUE THREAD

**Issue by LeaVerou** [color-js/elements#94]
<img width="1438" alt="image" src="https://github.com/color-js/elements/assets/175836/d9cc818a-f25e-4a3c-a289-b647b7ad0a1a">

**Comment by DmitrySharabin** [comment]
Actually, functional colors are parsed correctly if there are no commas. We use comma as a default separator when parsing entries:

https://github.com/nudeui/element/blob/eebac9359bf0eb32da7e3fb406716f35a7247677/src/props/types/dictionaries.js#L4

**Comment by LeaVerou** [comment]
I pushed a change to Nude Element that fixes this. I’m still unsure about it, I think it should probably be opt in for some of these pairs at least but oh well.
